---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Taxi Booking
  labels:
    app: Taxi Booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Taxi Booking
  template:
    metadata:
      labels:
        app: Taxi Booking
    spec:
      containers:
        - name: Taxi Booking
          image: username/Taxi Booking:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Taxi Management
  labels:
    app: Taxi Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Taxi Management
  template:
    metadata:
      labels:
        app: Taxi Management
    spec:
      containers:
        - name: Taxi Management
          image: username/Taxi Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Feedback
  labels:
    app: Feedback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Feedback
  template:
    metadata:
      labels:
        app: Feedback
    spec:
      containers:
        - name: Feedback
          image: username/Feedback:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Taxi Booking
  labels:
    app: Taxi Booking
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Taxi Booking


---


apiVersion: v1
kind: Service
metadata:
  name: Taxi Management
  labels:
    app: Taxi Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Taxi Management


---


apiVersion: v1
kind: Service
metadata:
  name: Feedback
  labels:
    app: Feedback
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Feedback

